SDC-7481. Spark Evaluator cluster mode hits NoClassDefFoundError on EscapeUtil
- EscapeUtil was moved from container to common. This causes EscapeUtil to not
  be available for SparkTransformers in cluster mode. So add common to
  spark-submit. Since EscapeUtil has no external dependencies, it is ok to
  ship the jar by itself.

Change-Id: I6069f11b4b2925defaf833b3055ed99ae8c7557b
Reviewed-on: https://review.streamsets.net/10754
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>