SDC-6744. MapR setup script: broken symlink to hive when MEP is not installed
When hive not installed, we create a broken symlink. Added check
if hive is installed. Added the check to HBase too just in case.
Then create symlinks only when they are installed.

This broken symlink causes pipeline failure:
FileNotFoundException: ...-mapr_5_2-lib/lib/*.jar (No such file or directory)

Change-Id: I8c2e99c1141f46eedba50ce58b6c8c459188bd17
Reviewed-on: https://review.streamsets.net/9261
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Rupal Shah <rupal@streamsets.com>
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>