SDC-14621. Kafka stages failing with NoClassDefFoundError
Making streamsets-utils a compile time dependency of kafka-common, so that TempKeytabManager is always included

Change-Id: Iec6803bf76b631adae2e20743ae193b39d9d2254
Reviewed-on: https://review.streamsets.net/c/datacollector/+/31897
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>
(cherry picked from commit ca989765cb7a043b468997e76e0197824235d8c9)
Reviewed-on: https://review.streamsets.net/c/datacollector/+/31905
Reviewed-by: Jeff Evans <jeff@streamsets.com>