SDC-15193. RPM: Needs to have SDC resources environment defined properly
EMR pipelines on marketplace was failing with

sdk.sdc_api.StartError: Unexpected error starting pipeline: java.lang.RuntimeException: ERROR: Serializing resources directory: 'resources': java.io.IOException: Failed to list contents of /opt/streamsets-datacollector/resources

The reason was el7 rpms define the SDC_RESOURCES to be /opt/streamsets-datacollector/resources, but the generally the env variable needs to be set to /var/lib/sdc-resource. This patch adds the env variable properly

Testing:
1. Installed the el7 RPM on docker and made sure the variable points to the right RESOURCES folder /var/lib/sdc-resources and also made sure SDC Directories in the SDC UI points rightly

===================================
JAVA OPTS                      : -Djava.security.manager -Djava.security.policy=file:///etc/sdc/sdc-security.policy -Xmx1024m -Xms1024m -server -XX:-OmitStackTraceInFastThrow  -Dsdc.dist.dir=/opt/streamsets-datacollector -Dsdc.resources.dir=/var/lib/sdc-resources
===================================

Change-Id: I50084ea75490d366f684af31fe4aabe73332e4a2
Reviewed-on: https://review.streamsets.net/c/datacollector/+/33664
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>