SDC-3511: Support Oracle Timestamp type in JDBC Origin
We're currently using a method getObject to retrieve TIMESTAMP type.
This method in Oracle JDBC driver however returns oracle.jdbc.TIMESTAMP
instead of expected java.sql.Timestamp (behavior is described in Oracle
documentation [1]). As the Oracle class is not even subclass of the java
one, things break with exception similar to the following:

IllegalArgumentException: Cannot convert TIMESTAMP field '2016-06-02
03:27:15.080069' to Date

One can workaround it by adding -Doracle.jdbc.J2EE13Compliant=true to
JAVA_OPTS declared in libexec/sdc-env.sh but that is quite tedious.
Hence I've replace the call for timestamp type from getObject to
getTimestamp that should always return java.sql.Timestamp instead.

Change-Id: If46cb48f4fcce0a374b3684eddeae9f58d5008b9
Links:
1: https://docs.oracle.com/cd/B28359_01/java.111/b31224/datacc.htm
Reviewed-on: https://review.streamsets.net/3677
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Junko Urata <junko@streamsets.com>