SDC-3950: Remove ignored test TestHiveTarget
The test case TestHiveTarget have consistently failed in last 4 jenkins
runs in two stage libs - HDP 2.2 and 2.4 in very weird way. Even though
that the test is being ignored (the class is annotated as such) either
junit or surefire plugin will get stuck on the test execution for the 10
minutes (which is test execution timeout). I also see this error at the
end of jenkins execution suggesting that something went wrong somewhere,
but not sure what and where:

Failed to execute goal
org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test
(default-test) on project streamsets-datacollector-hdp_2_4-lib:
Execution default-test of goal
org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed:
java.lang.RuntimeException:
org.apache.maven.surefire.report.ReporterException: When writing xml
report stdout/stderr: /tmp/stdout6959753557600863198deferred

Since the ignored test case is there for almost a year and I don't see
anyone working on fixit it, might I suggest to drop the test case to see
if it helps with the nightly?

Change-Id: I9cb5807a4e92ffc694ef9f08b15fb7d85e5ebc03
Reviewed-on: https://review.streamsets.net/4384
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Adam Kunicki <adam@streamsets.com>