SDC-6316. NoClassDefFoundError when Salesforce origin reaches end of data
Revert Avro exclusion from SDC-6254 - we need the Apache Commons transitive dependency
Revert removal of Jackson dependency from SDC-6266 - we need it after all

Change-Id: I88cdf1e38b01e761fb3054fa10d7d63ee89fd75c
Reviewed-on: https://review.streamsets.net/8536
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>