SDC-10521. HiveMetastore was missing hadoop-core dependency
* HiveMetastore was throwing a NoClassDefFoundError since HiveConf uses some Hadoop-Core classes.

Change-Id: I3bca2f83a54bc36dbf89d140883d3243609f0b7a
Reviewed-on: https://review.streamsets.net/c/18193
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Alejandro Abdelnur <tucu@streamsets.com>