SDC-15574. Linkage errors during stage library initialization are swallowed
Catch Throwable instead of just Exception (which covers NoClassDefFoundError and other class loading or runtime errors)

Fix NullPointerException in stopTask

Change-Id: I6427ab7e1a37b25abb22439108bf1f081ed3edef
Reviewed-on: https://review.streamsets.net/c/datacollector/+/34245
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>